package com.nrdc.policeHamrah.helper;

public enum PrivilegeNames {
    FILTER_USERS, ADD_USER, RESET_PASSWORD, LOGIN, LOGOUT, REMOVE_TOKEN, ADD_ROLE, EDIT_ROLE, EDIT_USER, REMOVE_ROLE, GET_SYSTEM_USERS, ACTIVE_USER, DE_ACTIVE_USER
}
